### ISSUE TITLE
SSL redirect from non www to www

### ISSUE THREAD

**Issue by aiomaster** [debops/ansible-nginx#141]
Hi,
if I have a certificate for domain.tld and www.domain.tld and want to redirect
https://domain.tld to https://www.domain.tld
How could I do this without using a full custom template?

I would like to have a new possibility to redirect these ssl stuff, too.
For that to work we have to listen to SSL port and include the certificates and return the new redirect location.

Do you have an idea to support that or is there a trick, that it could work with the current templates?

**Comment by drybjed** [comment]
It's not as pretty as you'd imagine, bit it works right now. All you need to do is define two `nginx` servers:
```yaml
nginx__servers:

  - name: 'www.domain.tld'
    filename: 'domain.tld'

  - name: 'domain.tld'
    filename: 'domain.tld_redirect'
    redirect: 'www.domain.tld'
    redirect_ssl: 'www.domain.tld'
```
The first server is your "main" configuration, you need to define all the locations, options there. The second server just redirects HTTP and HTTPS traffic from `domain.tld` to `www.domain.tld`.
