### ISSUE TITLE
Disabling server_welcome and server_localhost cause missing var error

### ISSUE THREAD

**Issue by andreasnrb** [debops/ansible-nginx#142]
Disabled the default sites but did not add any new this caused the error below. Setting server_welcome to enabled=true and the error is not generated.
*vars*
```
nginx_webroot_create: False
nginx_server_welcome:
  enabled: False
nginx_server_localhost:
  enabled: False
```
*ERROR*
```
fatal: [web]: FAILED! => {"failed": true, 
"msg": "the field 'args' has an invalid value, which appears to include a variable that is undefined. The error was: 'dict object' has no attribute 'name'. The error appears to have been in
'/home/andreas/.local/share/debops/debops-playbooks/roles/debops.nginx/tasks/nginx_servers.yml':
line 114, column 3, but maybe elsewhere in the file depending on the exact syntax problem. The offending line appears to be:
- name: Generate nginx server configuration\n  ^ here\n"} 
```
