### ISSUE TITLE
Pheonix Elixir Upstreams ?

### ISSUE THREAD

**Issue by niccolox** [debops/ansible-nginx#157]
trying to work out how to configure debops-nginx with an Elixir / Phoenix app as upstream? 

http://www.phoenixframework.org/docs/serving-your-application-behind-a-proxy

Phoenix generally runs on port 4000 but I actually want to have a number of apps and domains running with the same nginx as proxy

apologies if I am missing something super obvious

**Comment by drybjed** [comment]
The explanation on their site is totally unreadable. Did you recreate the `nginx` configuration they are suggesting already? Can you paste it here so we can see what's needed?

**Comment by niccolox** [comment]
lol

how is this?

https://medium.com/@a4word/setting-up-phoenix-elixir-with-nginx-and-letsencrypt-ada9398a9b2c

**Comment by niccolox** [comment]
the obvious question is where do I put the nginx config into a debops-nginx role? 

I am not even sure what variable I use?

**Comment by niccolox** [comment]
a couple of examples of Ansible Phoenix alternatives
https://github.com/HashNuke/ansible-elixir-stack
https://github.com/lnikkila/ansible-phoenix

**Comment by drybjed** [comment]
Since I assume that you are writing a role for `phoenix` (because you are, right?) then the relvant dependent variables for `debops.nginx` would be:
```yaml
phoenix__fqdn: 'phoenix.{{ ansible_domain }}'

phoenix__nginx__dependent_upstreams:
  - name: 'phoenix_upstream'
    server: 'localhost:4000'

phoenix__nginx__dependent_servers:
  - filename: 'phoenix'
    name: '{{ phoenix__fqdn }}'
    type: 'proxy'
    proxy_pass: 'http://phoenix_upstream'
```
Stick these in the `phoenix/defaults/main.yml` file, and in the playbook that runs the role, add:
```yaml
- name: Configure Phoenix
  hosts: phoenix-hosts
  become: True

  roles:

    - role: debops.apt_preferences
      tags: [ 'role::apt_preferences' ]
      apt_preferences__dependent_list:
        - '{{ nginx__apt_preferences__dependent_list }}'

    - role: debops.ferm
      tags: [ 'role::ferm' ]
      ferm__dependent_rules:
        - '{{ nginx__ferm__dependent_rules }}'

    - role: debops.nginx
      tags: [ 'role::nginx' ]
      nginx__dependent_upstreams:
        - '{{ phoenix__nginx__dependent_upstreams }}'
      nginx__dependent_servers:
        - '{{ phoenix__nginx__dependent_servers }}'

    - role: phoenix
      tags: [ 'role::phoenix' ]
```
That should do the trick. If you stick with using the TCP port for the application instead of the UNIX socket, I suggest using `debops.etc_services` role to register this port in the `/etc/services` file, it will look nicer in application output that use it.
