### ISSUE TITLE
Better support for proxy server definition

### ISSUE THREAD

**Issue by carlalexander** [debops/ansible-nginx#49]
Using `debops.nginx` with Varnish, I created a simple custom template to act as a proxy server.

```yml
wordpress_varnish_server:
  by_role: 'wordpress'
  enabled: True
  default: False
  type: 'custom'
  name: [ 'varnish.{{ wordpress_url }}' ]
  custom: |
    server {
      listen 80;
      server_name {{ wordpress_url }};
      access_log /var/log/nginx/varnish.{{ wordpress_url }}_access.log;
      error_log /var/log/nginx/varnish.{{ wordpress_url }}_error.log;
      client_max_body_size  {{ wordpress_php5_upload_size }};
      location / {
        proxy_set_header X-Real-IP  $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto http
        proxy_set_header X-Forwarded-Port 80
        proxy_set_header Host $host;
        proxy_pass http://varnish;
      }
    }
```

The issue is that it gets more complicated once we want to use SSL. You need two servers to handle HTTP requests. You'd need to support `debops.pki` although I disabled it. 

It'd be great if there was a way to use the default template with fewer defaults. There's a lot of stuff in the default template that isn't necessary when you create a proxy server.

Not sure what your thoughts are to handle that.

**Comment by drybjed** [comment]
I think the better solution would be to use a configuration like this (just a bare minimum to highlight the important bits):
```
wordpress_nginx_backend:
  enabled: True
  name:    [ '{{ wordpress_url }}' ]
  ssl:     False
  listen:  [ '[::]:8080' ]

  options: |
    client_max_body_size {{ wordpress_php5_upload_size }};

  location:
    '/': |
      proxy_set_header X-Real-IP $remote_addr;
      proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
      proxy_set_header X-Forwarded-Proto http;
      proxy_set_header X-Forwarded-Port 80;
      proxy_set_header Host $host;
      proxy_pass http://varnish;
```
So, what do we get from this configuration:

- SSL is specifically disabled, since you want to terminate SSL at `varnish`.

- `nginx` will listen on all IPv4 and IPv6 interfaces, on port `8080`. You need to handle the firewall separately to open that port for your hosts when you use multiple backends, and default `80` and `443` ports will be opened by the firewall regardless of what is set up in nginx, so that would need to be taken care of. Alternatively you can just design the set up to be multi-host with `varnish` frontend at one host and `nginx` backend on a separate host and drop the `item.listen` line, that will make all of that (paradoxically) much easier to deal with. DebOps is cluster-friendly like you couldn't believe.

- `nginx` role will handle the issue of `default_server ipv6only=off` by itself much better if you let it, rather than doing it by hand. That matters if/when you want to host multiple separate servers on a host. Although, if you change the listen port, it might not work as expected since each `listen` directive needs to handle these things separately. That further suggests to just use nginx on a separate host and let the role use port `:80` as it wants.

Since the "proxy" lines seem to be a common, generic thing, I suppose that i could add support for that setup in the `debops.nginx` role directly, so instead of writing all that you could do, for example:
```
nginx_server:
  name: [ '{{ wordpress_url }}' ]
  enabled: True
  ssl: False
  proxy: 'http://varnish/'

nginx_http_client_max_body_size: '{{ wordpress_php5_upload_size }}'
```

And that would handle all the needed code. I'll look into it when I release some other roles I have on my plate right now.

**Comment by carlalexander** [comment]
Following up on this from the [issue](https://github.com/carlalexander/debops-wordpress/issues/1) in DebOps for WordPress. I just tried a config similar to the one you suggested.

```yml
wordpress_varnish_server:
  by_role: 'wordpress'
  enabled: True
  default: False
  filename: 'varnish.{{ wordpress_url }}'
  name: [ '{{ wordpress_url }}' ]
  ssl: '{{ wordpress_nginx_ssl }}'
  pki_crt: '{{ wordpress_nginx_crt }}'
  pki_key: '{{ wordpress_nginx_key }}'
  redirect_code: '301'
  deny_hidden: False
  favicon: False
  options: |
    client_max_body_size  {{ wordpress_php5_upload_size }};

  location:
    '/': |
      proxy_set_header X-Real-IP $remote_addr;
      proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
      proxy_set_header X-Forwarded-Proto {% if wordpress_nginx_ssl is defined and wordpress_nginx_ssl }}https{% else %}http{% endif %};
      proxy_set_header X-Forwarded-Port {% if wordpress_nginx_ssl is defined and wordpress_nginx_ssl }}443{% else %}80{% endif %};
      proxy_set_header Host $host;
      proxy_pass http://varnish;
```

Good news, it works fine! 

I added `deny_hidden` and `favicon` to `False` to remove some unnecessary `location` section. It still generates some options that we don't need like `index` and `root`. There's no way to remove those. They're not breaking anything, but they're not needed either.

I changed `redirect_code` to `301`. Is there a reason why the HTTP to HTTPS redirect directive uses `307` by default? `301` makes a lot more sense for HTTP to HTTPS.

An issue is that `access_log` and `error_log` are tied to `item.name[0]`. This isn't ideal if I'd like to breakout the logs between varnish and what the backend server receives. I feel this is a change that makes sense either way. You should should have a way to overwrite `item.name[0]` as the default.

The `/nginx_status` location block is still there, but that's ok. This is because the config on the backend server doesn't work anymore. The backend will always receive a request from Varnish so it'll always be valid. It's actually an issue with my custom configuration as well. The reverse proxy will always forward the `stub_status` request and it'll always be valid. If anything, I'd like to be able to disable it on the backend server since it's not needed there.

Overall, I still feel this a workaround. That said, it's a good basis of what we need and don't need. Maybe all we need to do is add some missing logic to the `default` template. The `proxy` template could just change some of the defaults from the `default` template like `deny_hidden` and `favicon`.

**Comment by drybjed** [comment]
Current `debops.nginx` repository has truncated history, but you can find [the original commit](https://github.com/ginas/ginas/commit/291f2b50813c1dd93f2700cbbd58a94df0ede109) in the old incarnation of the project. Basically `Redirect 307` is the RFC-compilant way to temporarily redirect the browser, and I didn't want to use `301` by default because when you changed the subdomain, browsers would still go to the old site. Basically it gives more flexibility.

Separate redirect for HTTPS version? I suppose it could be added, why not. I'll add that to the todo list.

I'm not sure how `nginx` behaves without `root` and `index` set explicitly in the `server { }` block, does it use some kind of defaults? I imagine that proxy template wouldn't need them anyway, so they could be removed there.

Log handling in DebOps is underdeveloped in general. Probably adding a log server and pushing `nginx` logs through it could be interesting. @jwaibel is working on Graylog role, I'll probably add that to the stack at some point, and then some proper log redirection in `nginx` could be added.

**Comment by carlalexander** [comment]
Looked into `root` and `index`. Both have a default. You can find them here:
 - [index directive](http://nginx.org/en/docs/http/ngx_http_index_module.html#index)
 - [root directive](http://nginx.org/en/docs/http/ngx_http_core_module.html#root)

As you saw, I've been working on individual PRs to address some of the issues I found.

**Comment by carlalexander** [comment]
Here is the current working server configuration for the varnish proxy using the `default` template.
```yml
wordpress_varnish_server:
  by_role: 'wordpress'
  enabled: True
  default: False
  filename: 'varnish.{{ wordpress_url }}'
  name: [ '{{ wordpress_url }}' ]
  ssl: '{{ wordpress_ssl }}'
  pki_crt: '{{ wordpress_nginx_crt }}'
  pki_key: '{{ wordpress_nginx_key }}'
  root: False
  index: False
  deny_hidden: False
  favicon: False
  options: |
    client_max_body_size  {{ wordpress_php5_upload_size }};

  location:
    '/': |
      proxy_set_header X-Real-IP $remote_addr;
      proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
      proxy_set_header X-Forwarded-Proto {% if wordpress_ssl is defined and wordpress_ssl %}https{% else %}http{% endif %};
      proxy_set_header X-Forwarded-Port {% if wordpress_ssl is defined and wordpress_ssl %}443{% else %}80{% endif %};
      proxy_set_header Host $host;
      proxy_pass http://varnish;
```

The next step would be to extract the common configurations into a proxy template.
