### ISSUE TITLE
skip redirect to ssl

### ISSUE THREAD

**Issue by t3dev** [debops/ansible-nginx#59]
I am using debops and bootstrapped a single node from my local controll machine.
I have added some host_vars for a specific host in order to add another nginx config, see code below.
The created file for nginx still does redirect to the ssl site. Is there any way to disable this or maybe even another way to add a custom template file? Or, do you suggest to create a separate role? Would that simplify anything?
```
---
# List of nginx server definitions
nginx_servers: [ '{{ nginx_server_default }}', '{{ nginx_server_super }}']

# additional super nginx server
nginx_server_super:
  enabled: True
  type: 'php5'
  name: ['super.example.com']
  redirect_to_ssl: False
```

**Comment by drybjed** [comment]
To disable default redirection to HTTPS version of the site, set `item.ssl: False` in the server configuration:
```
nginx_server_super:
  enabled: True
  type: 'php5'
  name: ['super.example.com']
  ssl: False
```
The `item.redirect_to_ssl` option can be used to generate a redirection from HTTP to HTTPS, but without the HTTPS version of the config added by the template, so that HTTPS version can be generated separately.
