### ISSUE TITLE
Manage servers defined via multiple groups

### ISSUE THREAD

**Issue by andrenarchy** [debops/ansible-nginx#96]
I'm struggling to find a way to realize server configurations that are defined in the group vars of multiple groups but where the inventory maps these groups to the same host.

### Details
I have 2 groups (`frontend-servers`, `backend-servers`) to which the `debops.nginx` role is applied via the following playbook:
```yaml
---
- hosts: frontend-servers
  roles:
  - debops.nginx

- hosts: backend-servers
  roles:
  - debops.nginx
```

Furthermore, I define group variables for both groups:
```yaml
---
# group_vars/frontend-servers.yaml
nginx_servers:
- '{{ frontend_server }}'
frontend_server:
  enabled: True
  #...
```
```yaml
---
# group_vars/backend-servers.yaml
nginx_servers:
- '{{ backend_server }}'
backend_server:
  enabled: True
  #...
```

However, I have an inventory that maps both groups to the same host
```ini
[frontend-servers]
webserver
[backend-servers]
webserver
```
It seems like only one of the `nginx_servers` lists from the `group_vars` is respected. Is there another way to realize servers from multiple groups on the same host?

**Comment by carlalexander** [comment]
You can't use group variables if you want `debops.nginx` to create multiple vhosts like that. Instead, you can create two roles: `backend` and `frontend`. Inside those two roles, you'd create your `backend_server` and `frontend_server` variables. You'd then pass them to the `debops.nginx` dependency.

```yml
# meta/main.yml
---

dependencies:

  - role: debops.nginx
    nginx_servers:
      - '{{ nginx_server }}'
```

**Comment by drybjed** [comment]
Actually, you can, it's just a little more complicated:

In `inventory/group_vars/backend-servers/nginx.yml` put:
```yaml
nginx_backend_server:
  name: [ 'backend.{{ ansible_domain }}' ]
  enabled: True
```
In `inventory/group_vars/frontend-servers/nginx.yml` put:
```yaml
nginx_frontend_server:
  name: [ '{{ ansible_domain }}', 'www.{{ ansible_domain }}' ]
  enabled: True
```
Now, you need to merge them. To do it, you can create a new inventory group for merged hosts:
```ini
[nginx-merged-hosts:children]
frontend-servers
backend-servers
```
And, in `inventory/group_vars/nginx-merged-hosts/nginx.yml` put:
```yaml
nginx_servers: '{{ nginx_merged_servers }}'

nginx_merged_servers:
  - '{{ nginx_frontend_server | d([]) }}'
  - '{{ nginx_backend_server  | d([]) }}'
```
Now, when you add your host to `[nginx-merged-hosts]` group, it should have both configurations present.

(All written on the fly, not tested, but I think it should work)
